# NAME="Ubuntu"
# VERSION="14.04.6 LTS, Trusty Tahr"
# ID=ubuntu
# ID_LIKE=debian
# PRETTY_NAME="Ubuntu 14.04.6 LTS"
# VERSION_ID="14.04"
# HOME_URL="http://www.ubuntu.com/"
# SUPPORT_URL="http://help.ubuntu.com/"
# BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_version = "20191107.0.0"
end
